<a href="https://colab.research.google.com/github/rswijesena/AI/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [3]:
print(torch.cuda.is_available())

False


introduction to **Tensors**

In [7]:
## introductions to tensors

scaler = torch.tensor(7)
print(scaler)
print(scaler.item())



tensor(7)
7


In [8]:
#Vector

vector = torch.tensor([7,7])
print(vector)
print(vector.shape)

tensor([7, 7])
torch.Size([2])


In [9]:
# Create a random tensor

random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.shape)

tensor([[0.3573, 0.3718, 0.6870, 0.8999],
        [0.4981, 0.7247, 0.4926, 0.7245],
        [0.1243, 0.3944, 0.6200, 0.0708]])
torch.Size([3, 4])


In [10]:
random_imnage_size_tensor = torch.rand(size=(224,224,3)) #height #width #color Channel
print(random_imnage_size_tensor.shape)

torch.Size([224, 224, 3])


In [11]:
#Create Tensor of all Zero

zeros = torch.zeros(size=(3,4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [12]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
torch.range(0,10)

<ipython-input-13-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
torch.arange(start=0,end=10,step=2)

tensor([0, 2, 4, 6, 8])

In [18]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0],dtype=None,device=None,requires_grad=False)
print(float_32_tensor)

tensor([3., 6.])
